# Generated by Django 6.0.2 on 2026-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_service",
            "0002_alter_mailing_options_alter_mailingattempt_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Введите комментарий",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(
                help_text="Введите адрес эл. почты",
                max_length=100,
                unique=True,
                verbose_name="Почта",
            ),
        ),
    ]
