# Generated by Django 6.0.2 on 2026-02-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0003_alter_recipient_comment_alter_recipient_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_time"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время попытки"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailing_service.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailing_service.recipient",
                verbose_name="Получатель",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ответ сервера/Ошибка"
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("fail", "Не успешно")],
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
