# Generated by Django 6.0.2 on 2026-03-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0005_mailing_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
